import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div className="bg-gray-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Right click the animation to copy the styling</h1>

        <div>hello</div>
      </main>

      <footer>built by alex</footer>
    </div>
  )
}

export default Home
